version: '3.4'

services:
  cache-products.redisserver:
    ports:
      - "6379:6379"
  cache-products.sqlserver:
    environment:
      - MSSQL_SA_PASSWORD=Abc@1234
      - ACCEPT_EULA=Y
    ports:
      - "1400:1433"
    volumes:
      - mssql_data:/var/opt/mssql
  cache-products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=3443
    ports:
      - "81:80"
      - "3443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro